"""Wrap a rendered subgraph in a target-specific context block.

:func:`~graphex.formatter.format_subgraph` produces the *body* — a Markdown view
of the selected nodes and their relationships. This module wraps that body in the
boilerplate each consuming target expects so it can be pasted straight in:

- ``claude``: XML-ish ``<knowledge_graph_context>`` tags, the convention Claude
  follows for delimiting injected context.
- ``chatgpt``: a ``## Relevant codebase context`` section behind a short
  system-style instruction line.
- ``claudemd``: a ``## Knowledge Graph Context`` section sized to drop into a
  ``CLAUDE.md`` / ``AGENTS.md`` agent-instruction file.

The body is always the formatter's Markdown output, unchanged — this module only
adds the surrounding frame.
"""

from __future__ import annotations

from graphex.formatter import format_subgraph
from graphex.models import KnowledgeGraph


def _query_label(query: str) -> str:
    """A human-readable phrase naming the query, with a fallback when empty."""
    return query.strip() or "the current task"


def _wrap_claude(body: str, query: str) -> str:
    """Wrap the body in ``<knowledge_graph_context>`` tags for Claude."""
    intro = (
        f"The following knowledge-graph context was retrieved for the query: "
        f"{_query_label(query)}."
    )
    return "\n".join(
        (
            "<knowledge_graph_context>",
            intro,
            "",
            body.rstrip("\n"),
            "</knowledge_graph_context>",
            "",
        )
    )


def _wrap_chatgpt(body: str, query: str) -> str:
    """Wrap the body in a ``## Relevant codebase context`` section for ChatGPT."""
    instruction = (
        "Use the relevant codebase context below to answer the query "
        f"({_query_label(query)}). Treat it as authoritative background."
    )
    return "\n".join(
        (
            instruction,
            "",
            "## Relevant codebase context",
            "",
            body.rstrip("\n"),
            "",
        )
    )


def _wrap_claudemd(body: str, query: str) -> str:
    """Wrap the body in a ``## Knowledge Graph Context`` section for CLAUDE.md."""
    note = (
        f"_Generated by graphex for the query: {_query_label(query)}. "
        "Paste into your CLAUDE.md / AGENTS.md to keep this context on hand._"
    )
    return "\n".join(
        (
            "## Knowledge Graph Context",
            "",
            note,
            "",
            body.rstrip("\n"),
            "",
        )
    )


def export_context(
    graph: KnowledgeGraph,
    stats: dict,
    query: str,
    format: str = "claude",
    scores: dict[str, float] | None = None,
) -> str:
    """Render a subgraph and wrap it in a target-specific context block.

    Args:
        graph: The already-pruned subgraph to render.
        stats: Budget accounting (see :func:`graphex.budget.select_subgraph`).
        query: The originating query, named in the wrapping boilerplate and
            echoed in the Markdown body.
        format: One of ``"claude"`` (default), ``"chatgpt"`` or ``"claudemd"``.
        scores: Optional ``{node_id: score}`` forwarded to the formatter so the
            body orders nodes by score and surfaces them.

    Returns:
        The wrapped context string, ready to paste into the target.

    Raises:
        ValueError: If ``format`` is not one of the supported values.
    """
    # Suppress the decorative box header: a pasted context block shouldn't carry
    # Graphex's internal token-budget meta-noise into the LLM's prompt.
    body = format_subgraph(
        graph, stats, format="markdown", scores=scores, query=query, include_header=False
    )

    if format == "claude":
        return _wrap_claude(body, query)
    if format == "chatgpt":
        return _wrap_chatgpt(body, query)
    if format == "claudemd":
        return _wrap_claudemd(body, query)
    raise ValueError(f"unknown format {format!r}; expected 'claude', 'chatgpt' or 'claudemd'")
